apiVersion: v1
kind: ResourceQuota
metadata:
  name: easyshop-quota
  namespace: easyshop
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1.5Gi
    limits.cpu: "2"
    limits.memory: 3Gi
    pods: "15"